### ISSUE TITLE
Add support for users without JavaScript

### ISSUE THREAD

**Issue by MissAllSunday** [MissAllSunday/Breeze#15]
I would like to add some basic support for those users that doesn't have JavaScript for whatever reason, in theory it wouldn't be that hard since BreezeAjax can be called with an standard http request, in fact, thats how I do debugging stuff by sending plain http get request to breezeajax action providing the correct data is send of course.

Providing basic support for adding and deleting both status and comments should be enough.

**Comment by MissAllSunday** [comment]
Been working on supporting users without JavaScript, I thought it was going to be a lot more difficult but so far its been pretty easy.

The real pain in the ass is applying a message system to let the user know that their actions went good/wrong, I took the lazy way and appended a lot of params to the url where the users are redirected after the process is done and set some divs on the template.

So far its working good, I can post new status an comments with a browser that has JS disable, the real question is, what will happen with a browser that does support JS?  what process will take the lead and priority, the plain http request or the ajax one? what will happen if a browser takes both as valid?

**Comment by XinYenFon** [comment]
Did you made a research about this ? How many people (in percentage) not using JS? Currently its not necessary IMO.

**Comment by MissAllSunday** [comment]
Is not really that difficult, in fact, most of the CRUD actions are already done, the only things I need to change is how the comments are handled since for every message I create a form and I need to use some type of identifier to know which form I'm currently working on, I used the status ID as a unique identifier, the only thing I need to do is pass that identifier to the server so I can grab the correct info when a comment is posted without javascript.

Also, there is an user page where the user can delete/mark as read all their notifications, this page needs to be as simple as possible, that includes not using javascript on it.
