### ISSUE TITLE
Add support for 5.2?

### ISSUE THREAD

**Issue by MissAllSunday** [MissAllSunday/Breeze#22]
I don't know how many SMF users are still using PHP 5.2, don't know if it's even worth.

Breeze is pretty much compatible with 5.2 except for two files that happens to be the neuralgic center of the mod:
- BreezeController
- BreezeContainer

In theory I could replace the closures with create_function(), the problem is, the use() keyword, I don't know of any real way to replace it.

**Comment by XinYenFon** [comment]
If there is no demand for this, you just waste your time. I think for now you have to focus on main product not its support range.

**Comment by MissAllSunday** [comment]
Bad idea.
