### ISSUE TITLE
Service Providers

### ISSUE THREAD

**Issue by MissAllSunday** [MissAllSunday/Breeze#234]
Replace the current mapper array with service providers for each type of service currently used.

**Comment by tyrsson** [comment]
Can I get an example of one of these? I might have a few ideas. Are you using psr-11 here?

**Comment by MissAllSunday** [comment]
@tyrsson I'm afraid not! this was wrote with the intention of immediately tackle it, meaning I had the solution in my head and didn't bother to write it down somewhere. Now time has passed and I have no idea what I was talking about.

I still use a mapper Config/MapperAggregate.php to load the needed classes, I need to do some tests to know if I still needed it since I already use composer/autoload

**Comment by tyrsson** [comment]
Maybe I am crazy but is this not what PSR-11 is for?

**Comment by MissAllSunday** [comment]
It is, I'm using a mapper to [registry the needed services](https://container.thephpleague.com/4.x/)  Theres a feature for autoregistering but I don't want to use it at this moment
