### ISSUE TITLE
load components

### ISSUE THREAD

**Issue by MissAllSunday** [MissAllSunday/Breeze#260]
re-do the way components are loaded, group them by page to avoif loading components that aren't going to be used

**Comment by tyrsson** [comment]
Its possible to use PSR-11 for this, even in the 2.1.x branches. Just takes a little work :)

**Comment by MissAllSunday** [comment]
@tyrsson Thanks! by components I was referring to the way I used to load Vue components. the mod no longer uses Vue (it now uses React instead) so this no longer applies.

**Comment by tyrsson** [comment]
I would look into htmx. It will change your life.

**Comment by MissAllSunday** [comment]
yeah although I will check svelte first
