### ISSUE TITLE
Error when viewing profiles

### ISSUE THREAD

**Issue by Shades75** [MissAllSunday/Breeze#310]
When logged in as a regular member, I click on the admin profile/wall and get this error:

1rst time clicked:

> An Error Has Occurred!
The database value you're trying to insert does not exist: users

2nd time clicked:

> https://mysite.com/index.php?action=profile;u=1
Cannot use string offset as an array

#0 /index.php(134): fatal_error(string, string)
#1 {closure}(Error)
#2 {main}

Here are the Admin error logs:

> https://mysite.com/index.php?action=profile;u=1
Cannot use string offset as an array

#0 /index.php(134): fatal_error(string, string)
#1 {closure}(Error)
#2 {main}

> https://mysite.com/index.php?action=profile;u=1
The database value you're trying to insert does not exist: users
Function: loadMemberDataApply
File: /xxxxx/xxxxx/mysite.com/Sources/Load.php
Line: 1109

#0 /Sources/Subs-Db-mysql.php(873): error_backtrace(string, string, integer, string, integer)
#1 replacement__callback(array)
#2 /Sources/Subs-Db-mysql.php(1084): preg_replace_callback(string, array, string)
#3 /Sources/Load.php(1109): query(string, string, array)
#4 /Sources/Breeze/BreezeTools.php(286): loadMemberData(array, boolean, string)
#5 /Sources/Breeze/BreezeUser.php(725): loadUserInfo(array)
#6 /Sources/Breeze/BreezeUser.php(121): breezeTrackViews()
#7 /Sources/Profile.php(731): breezeWall(string)
#8 /index.php(185): ModifyProfile()
#9 {main}

> https://mysite.com/index.php?action=profile;u=1
2: array_keys() expects parameter 1 to be array, string given
File: /xxxxx/xxxxx/mysite.com/Sources/Breeze/BreezeUser.php
Line: 725

#0 /Sources/Breeze/BreezeUser.php(725): array_keys(string)
#1 /Sources/Breeze/BreezeUser.php(121): breezeTrackViews()
#2 /Sources/Profile.php(731): breezeWall(string)
#3 /index.php(185): ModifyProfile()
#4 {main}

> https://mysite.com/index.php?action=profile;u=1
8: Array to string conversion
File: /xxxxx/xxxxx/mysite.com/Sources/Breeze/BreezeUser.php
Line: 710

#0 /Sources/Breeze/BreezeUser.php(121): breezeTrackViews()
#1 /Sources/Profile.php(731): breezeWall(string)
#2 /index.php(185): ModifyProfile()
#3 {main}

As I posted on the SMF board, I tested again and after turning on the wall in each members profile settings, member to member gets the same errors as above when viewing other members profile/wall.

Logged in as admin, I can see and comment on every member profile/wall but not when logged in as a regular member.

**Comment by MissAllSunday** [comment]
Addressed at [SMF's forum](https://www.simplemachines.org/community/index.php?msg=4092678)
