### ISSUE TITLE
a tiny "my mood" feature?

### ISSUE THREAD

**Issue by MissAllSunday** [MissAllSunday/Breeze#59]
It is relatively easy to use the custom profile system to add more fields and I already did something similar on the award mod.

**Comment by XinYenFon** [comment]
if you have a chance take a look at Facebook's "What are you doing?" part. Beside mood feature it could be better for all :)

**Comment by MissAllSunday** [comment]
The Facebook thing is just too much, I was just thinking on a text field where users would be able to change their mood.

**Comment by MissAllSunday** [comment]
Can't believe I tracked this twice, does this mean I really really need to add this :P  #83
