### ISSUE TITLE
Change the copyright year on all files

### ISSUE THREAD

**Issue by MissAllSunday** [MissAllSunday/Breeze#67]
Should be 2011, 2012, 2013

**Comment by MissAllSunday** [comment]
mmm, this is still confusing... I began to work on this on 2011 but 1.0 will (most likely) be released on 2013...   so, question is, do I need to set the year from where I started to work on it or when it was finally released?

mmm, as always, no one around to actually answer... oh well, I will go the safer route and put both 2011 and 2013.

**Comment by XinYenFon** [comment]
I'm not sure this is fixed for you completely or not but yes 2013 is right also afaik you can do 2011-2013

**Comment by MissAllSunday** [comment]
I spoke to a few people involved on foss software and they all agree that I should use the year I started development on, which is 2011 however, it is also valid to assign a copyright on the actual year of release, meaning my copyright should be 2011, 2013.

**Comment by MissAllSunday** [comment]
I suppose at this rate I will have to change the copy to 2011, 2014 :P
