### ISSUE TITLE
Likes

### ISSUE THREAD

**Issue by MissAllSunday** [MissAllSunday/Breeze#73]
Instead of reinventing the wheel I should just use an already existing likes mod like https://github.com/Joker-SMF/SMF-Likes

**Comment by XinYenFon** [comment]
I suggest you to not, because many forums who is gonna use your modification will and probably be using like system. My suggestion is create addons for integration. I know it can be more work for you but trust me it worths because there are 4 (or 5 or 3 not really know) like plug-in (paid-free).

**Comment by MissAllSunday** [comment]
I don't plan to support all of them, certainly not the paid ones as I would have to purchase them just to offer integration, I rather prefer not to spent any more money on Breeze.

Coding my own is not going to happen, too much work and not enough motivation.

**Comment by MissAllSunday** [comment]
Theres a likes feature on 2.1 and I should use that.
