### ISSUE TITLE
Follow/Followers system?

### ISSUE THREAD

**Issue by MissAllSunday** [MissAllSunday/Breeze#93]
Besides the buddy system, does it make sense to have a follow system?  

Does it makes more sense to replace the buddy system with a follow system?

In terms of coding it will be easier... since it there only will be a one way out, either you follow or unfollow a person and the other person doesn't have to find out or approve.

**Comment by ghost** [comment]
I'd say go for the following system. :)

**Comment by MissAllSunday** [comment]
Yep, I'm more inclined for a follow system too, gotta tag this for a next version though.

**Comment by MissAllSunday** [comment]
The buddy system is going the be re factored in 1.1 so I'm closing this one, at least for 1.1.
