### ISSUE TITLE
Say, Where's the Profile Wall?

### ISSUE THREAD

**Issue by ghost** [MissAllSunday/Breeze#94]
Maybe I'm just a few fries short of a Happy Meal, but I don't see how the user's profile looks any different after I install the mod. I looked around for settings and couldn't find them.

Installed the "develop" branch via the package manager.

![screenshot-3](https://f.cloud.github.com/assets/1619395/1434021/3bfbd40a-410a-11e3-9b9d-4b9c050dc205.png)

**Comment by MissAllSunday** [comment]
After install the mod should re-direct you to its settings page at action=admin;area=breezeadmin

The mod by default is disable and it is also disable for all users, on the general settings tab action=admin;area=breezeadmin;sa=settings  you can select to enable the wall for all users or just enable it on general and let users to manually enable the wall themselves.

After the wall has been enable, the summary page gets moved to action=profile;area=static

Perhaps the hooks weren't applied, are you using php 5.4? I haven't test the whole pass by reference issue on php5.4

**Comment by ghost** [comment]
I'm on PHP 5.5.5, so you're probably right, I bet the hooks are broken. Those two actions seem to have no function. It  just shows the main admin center page.

**Comment by MissAllSunday** [comment]
Oh, it turned out to be a silly mistake of mine :(

Thanks for the report! :)

**Comment by ghost** [comment]
Awesome. I'll give it another try shortly.
